version: "3.8"

services:
  metabase:
    image: s36technology/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MB_EMBEDDING_APP_ORIGINS: "http://localhost"
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data: